
-- 2. CREACION DEL USUARIO

CREATE USER SISUSR PROFILE DEFAULT IDENTIFIED BY sisusr; 
-- 3. OTORGAR PERMISOS

	GRANT "CONNECT" TO "SISUSR";
	GRANT "RESOURCE" TO "SISUSR";
	GRANT ALTER ANY INDEX TO "SISUSR";
	GRANT ALTER ANY SEQUENCE TO "SISUSR";
	GRANT ALTER ANY TABLE TO "SISUSR";
	GRANT ALTER ANY TRIGGER TO "SISUSR";
	GRANT CREATE ANY INDEX TO "SISUSR";
	GRANT CREATE ANY SEQUENCE TO "SISUSR";
	GRANT CREATE ANY SYNONYM TO "SISUSR";
	GRANT CREATE ANY TABLE TO "SISUSR";
	GRANT CREATE ANY TRIGGER TO "SISUSR";
	GRANT CREATE ANY VIEW TO "SISUSR";
	GRANT CREATE PROCEDURE TO "SISUSR";
	GRANT CREATE PUBLIC SYNONYM TO "SISUSR";
	GRANT CREATE TRIGGER TO "SISUSR";
	GRANT CREATE VIEW TO "SISUSR";
	GRANT DELETE ANY TABLE TO "SISUSR";
	GRANT DROP ANY INDEX TO "SISUSR";
	GRANT DROP ANY SEQUENCE TO "SISUSR";
	GRANT DROP ANY TABLE TO "SISUSR";
	GRANT DROP ANY TRIGGER TO "SISUSR";
	GRANT DROP ANY VIEW TO "SISUSR";
	GRANT INSERT ANY TABLE TO "SISUSR";
	GRANT UPDATE ANY TABLE TO "SISUSR";
	GRANT QUERY REWRITE TO "SISUSR";
	GRANT SELECT ANY TABLE TO "SISUSR";
	GRANT UNLIMITED TABLESPACE TO "SISUSR";